### ISSUE TITLE
Check integrity of pid file

### ISSUE THREAD

**Issue by JonRoma** [cites-illinois/awscli-login#5]
The application has a tiny bit of awkwardness with its pid file, in cases when the running process with that pid can't be found. 

More user-friendly behavior might be to check the pid file. If the process referred to by the contents of the pid file doesn't exist or isn't owned by the running user, remove the pid file and log in anew.

**Comment by ddriddle** [comment]
@dmrzzz Release v0.1.0a4 should resolve this issue. Please follow up if you continue to have problems. Thank you for reporting this issue!
