### ISSUE TITLE
SyntaxError on Python 3.5.2

### ISSUE THREAD

**Issue by dmrzzz** [cites-illinois/awscli-login#8]
Using Python 3.5.2 which is packaged for xubuntu 16.04.4 LTS, the plugin causes awscli to fail with a SyntaxError:
```
dmrz@golbez:~$ aws --version
aws-cli/1.15.16 Python/3.5.2 Linux/4.4.0-121-generic botocore/1.10.16

dmrz@golbez:~$ aws configure set plugins.login awscli_login

dmrz@golbez:~$ aws --version
Traceback (most recent call last):
  File "/home/dmrz/.local/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/home/dmrz/.local/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/home/dmrz/.local/lib/python3.5/site-packages/awscli/clidriver.py", line 58, in main
    driver = create_clidriver()
  File "/home/dmrz/.local/lib/python3.5/site-packages/awscli/clidriver.py", line 69, in create_clidriver
    event_hooks=emitter)
  File "/home/dmrz/.local/lib/python3.5/site-packages/awscli/plugin.py", line 44, in load_plugins
    modules = _import_plugins(plugin_mapping)
  File "/home/dmrz/.local/lib/python3.5/site-packages/awscli/plugin.py", line 58, in _import_plugins
    plugins.append(__import__(path))
  File "/home/dmrz/.local/lib/python3.5/site-packages/awscli_login/__init__.py", line 10, in <module>
    from awscli_login.__main__ import main, logout
  File "/home/dmrz/.local/lib/python3.5/site-packages/awscli_login/__main__.py", line 103
    exp: Exception
       ^
SyntaxError: invalid syntax
```

It looks like you're using some brand-new syntax here?  https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-pep526

In my opinion, it would be most convenient for users if the module is able to broadly support all recent versions of Python; awscli itself supports any 3.3+ according to https://docs.aws.amazon.com/cli/latest/userguide/installing.html   OTOH if there is a need to support 3.6+ only, a note to that effect in the README would be very helpful.

**Comment by dmrzzz** [comment]
Neglected to mention that this is using 0.1.0a3 from pip:
```
dmrz@golbez:~$ pip3 list | grep awscli-login
awscli-login (0.1.0a3)
```

**Comment by dmrzzz** [comment]
FWIW I have confirmed that removing this syntax in https://github.com/dmrzzz/awscli-login/commit/5c4b13160dab26bf0fbf30e97eefe888a79b621a solves my problem.  Those changes to src/awscli_login/config.py are far too clumsy to submit a PR as is, though.  Let me know if you have thoughts on how best to fix this.

**Comment by ddriddle** [comment]
@dmrzzz so the best solution that retains the type hints and is compatible with Python 3.5 is to use syntax like this:
```
exp = None  # type: Exception
```
As opposed to the nicer 3.6 syntax:
```
exp: Exception
``` 
You can see more examples of this here if you are curious:

http://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html

Thank you for reporting the problem. I have put together a working patch this morning. I need to do a bit more testing and cleaning up before I make another release. I am going to try and make a release tonight.

**Comment by ddriddle** [comment]
@dmrzzz Release v0.1.0a4 should resolve this issue. Please follow up if you continue to have problems. Thank you for reporting this issue!
